### PR TITLE
refactor: convert to an oclif plugin

### PR DESCRIPTION
**Pull request by amphro**
I started from scratch rather than using the upgrade path. This converts the project to typescript, commands to oclif, and updates the linting rules. I still need to check on a couple things tomorrow but it would be great if you could test the commands. I only ran through the trace commands.

BREAKING CHANGE: converting to an oclif plugin changes the import and file structure

### CODE REVIEW

**Comment by combizs** [comment]
@wadewegner, @amphro, any updates on this?  Currently, this plugin won't install using the `sfdx-cli@7.1.*`; users have to force to the previous 6.* version.

**Comment by amphro** [comment]
I know Wade has been traveling a bunch. I haven't merged this because I don't have enough knowledge on all the commands. Any change you would be willing to pull this branch down locally @combizs and give some of the commands a test for me? Make sure I didn't break anything?

**Comment by combizs** [comment]
@amphro Yes, I can pull it down locally, link it and test to see if it's successful for our workflow right now.

**Comment by combizs** [comment]
@amphro, I just pushed a change to fix something that broke for me; change coming in as [PR for your branch](https://github.com/wadewegner/sfdx-waw-plugin/pull/20)

**Comment by amphro** [comment]
Good catch. Any other issues or are things generally working?

**Comment by combizs** [comment]
> Good catch. Any other issues or are things generally working?

From what I noticed, it created the connected app as we described.  I didn't see any breaking changes outside our use case or the one that got merged. 👍Great job on conversion to an oclif plugin, I was hesitant to stay on the cli@6.

**Comment by wadewegner** [comment]
Thank you both. I'm back from travels and looking at this now.

**Pull request merged**
